# CI/CD workflow for VitePress documentation site
name: Build and Release

on:
  # Build check on every push and create release on tags
  push:
    branches: ["main", "develop"]
    tags:
      - 'v*'
  
  # Build check on pull requests
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for creating releases and uploading artifacts
permissions:
  contents: write
  packages: write

jobs:
  # Build job - runs on all pushes and PRs
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with VitePress
        run: npm run docs:build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-build-${{ github.sha }}
          path: .vitepress/dist
          retention-days: 30

  # Release job - only runs on tags
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with VitePress
        run: npm run docs:build
      
      - name: Create release archive
        run: |
          cd .vitepress/dist
          tar -czf ../../docs-site-${{ github.ref_name }}.tar.gz .
          cd ../..
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docs-site-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
